### ISSUE TITLE
Branch off Existing Lore

### ISSUE THREAD

**Issue by DarkRisings** [DarkRisings/src#4]
We need to have an open discussion about where in DR lore history we want this game to branch from.

We know the following: 

- The branch occurs sometime BEFORE Lasombra / vampires were destroyed
- Some event caused a planar shift resulting in an alternate timeline where this game exists

Discuss when and how this occurs.

**Comment by figgers3036** [comment]
If we're going to break the timeline, let's break the timeline.

Whatever event we choose, it's already thrown things off a ton.  So why choose just one time period to toss on over?  This could be a world where Astyron's in the middle of experiencing being a mortal, Vlenarov is running around, Flocrian is a vampire, and Elminars is still a Gypsy.  That is, vampires exist with Lilith and Kiyanne like we want them, but our lore is a jumbled mess.

DR's lore is already a jumbled mess and we're trying to lure in players that don't know what happened over the past 5 years.  Let's not penalize them for that, but instead let them come in from what they remember.  Their history turns into DR's history, and we're all kind of thrown together like we're suddenly starring in Lost.  It helps them get up to speed quickly with what they know already, and helps them discover where everyone else it coming from.  Maybe one person only remembers up to Savannah as Elder, while another remembers Nod coming back, but in the end it shouldn't matter since it forces players to engage to figure out where one another is at and gives no one a monopoly on knowing the latest and greatest on what's been going on in DR.

That is, it legitimizes where anyone's memory of DR lore is at.

**Comment by avalane** [comment]
The last big event that drew a lot of people was when Lilith came back and Aequitas was born. I think we could do something along that line where there was a great split. Write up some type of lore that was within that time frame where the planar shift happened. A great ripping tear and the world spun. We awoke to find that things were the same...but not the same, kind of spin off. It would definitely have to be fleshed out but I definitely think we need to add some type of history explaining what happened in some type of way.

**Comment by trseagro** [comment]
Hehe, I am not adverse to suggesting the events around Liliths apparent death.  Flocrian and some others were messing with things to resurrect her.  And we all know divine and vampires don't mix.

**Comment by figgers3036** [comment]
Yeah Fil and Floc were working on that, then Rehanea came in and roflstomped all over the guild...  I don't know if I want to go down that path, though?  End-era Lilith got really lame...  

I like the idea of Aequitas and Lilith all happening at the same time caused a tear and a shift, and hurled people from all eras of Rhia to be pushed into where we are now.

Our beginning era stuff would be fun too, with "figure out what happened."  There's no reason cross-time events wouldn't kick off the event, if Floc and Fil actually went off to resurrect Lilith, Aequitas came around, and Lilith reappearing is just too much.  We could come up with time moving in all sorts of different ways...  but I'm afraid that might be a bit too out there and game-y.

Anyway, Kiyanne was working with Fil on how to resurrect Lilith.  We could do that, but I'm uncomfortable turning it into "Look at what Fil did omg."

**Comment by DarkRisings** [comment]
We could say Zaly did it

**Comment by figgers3036** [comment]
Yeah.  If we wanted to toss in something about BoPs going away in this timeline or whathaveyou, Fil was trying to build one too, we could add in that going awry.

**Comment by trseagro** [comment]
Actually the BoPs are a great idea.  We could simply say the library / volcanic island finally went too.

**Comment by trseagro** [comment]
If we wanted to really shake the snow globe up, we could have the event be the ascendency of Lilith.  (I.E. make her a god.)  The rebalancing of reality could be manifest in the changes we make then.

**Comment by avalane** [comment]
Ooooo good one

**Comment by figgers3036** [comment]
Lilith reaching a level of demi-godhood would be a clean break with old DR lore.  I like that idea.
